project:
  type: website

website:
  title: "Dian's Blog"
  navbar:
    right:
      - article.qmd
      - icon: github
        href: https://dian-sheng.github.io
      
format:
  html:
    theme: cosmo
    css: styles.css

execute: 
  freeze: auto



